### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by 2023SMART** [dfki-ric-underactuated-lab/mini-cheetah-tmotor-python-can#11]
hi i'm making quadruped robot like you, using ak-70-10. i use your code but my motors don't move.
And i have this error

Traceback (most recent call last):
  File "mini-cheetah-tmotor-python-can/Actuator.py", line 94, in <module>
    multi_motor_controller.send_command_to_all_motors(commands)
  File "mini-cheetah-tmotor-python-can/Actuator.py", line 43, in send_command_to_all_motors
    motor.send_rad_command(
  File "/home/smart/mini-cheetah-tmotor-python-can/src/motor_driver/canmotorlib.py", line 498, in send_rad_command
    rawMotorData = self.decode_motor_status(motorStatusData)
  File "/home/smart/mini-cheetah-tmotor-python-can/src/motor_driver/canmotorlib.py", line 351, in decode_motor_status
    self._recv_bytes.bytes = data_frame
  File "/home/smart/.local/lib/python3.8/site-packages/bitstring/bitarray_.py", line 126, in __setattr__
    super().__setattr__(attribute, value)
  File "/home/smart/.local/lib/python3.8/site-packages/bitstring/bits.py", line 616, in _setbytes
    self._bitstore = BitStore.frombytes(bytes(data))
TypeError: cannot convert 'NoneType' object to bytes

what can i do?

**Comment by vyas-shubham** [comment]
Hello,

It looks like the received bytes are none and hence you see a `NoneType` in your error. My guess would be that the hardware communication isn't working as expected. Could be because of faulty cables, connections, or the motor ID.
